version: '3'
services:
    node:
        build: .
        porst:
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        enviromment:
            - PORT=8080
    postgres:
        build: ./database/
        ports:
            ${POSTGRES_PORT}:${POSTGRES_PORT}
        enviromment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            