version: "3"

services:
  # app:
  #   image: service
  #   build: .
  #   restart: always
  #   depends_on:
  #     - postgres
  #   networks:
  #     - net-custom
  #   environment:
  #     PORT: ${PORT}
  #   ports:
  #     - ${PORT}:${PORT}
  #   volumes:
  #     - ./logs:/app/logs
  #     - .:/app/
  #     - /app/node_modules

  postgres:
    image: postgres
    build: ./database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - net-custom
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ${POSTGRES_VOLUME_PATH}

networks:
  net-custom:
    driver: bridge

